# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-16 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_django_upgrade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("As", "Asset"),
                    ("Li", "Liability"),
                    ("Eq", "Equity"),
                    ("In", "Income"),
                    ("Ex", "Expense"),
                ],
                default="Li",
                max_length=2,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="A small image that will be added to lists.",
                upload_to="logos",
            ),
        ),
        migrations.AlterField(
            model_name="roleaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("Bank", "Bank account"),
                    ("Cash", "Cash account"),
                    ("Sale", "Sale account"),
                ],
                max_length=4,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pen", "Pending"),
                    ("Com", "Committed"),
                    ("Rej", "Rejected"),
                ],
                max_length=3,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="type",
            field=models.CharField(
                choices=[
                    ("Pen", "Pending"),
                    ("Com", "Committed"),
                    ("Rej", "Rejected"),
                ],
                max_length=3,
                verbose_name="type",
            ),
        ),
    ]
