# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_python3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='May be used for date of the transaction if not today.', verbose_name='date'),
        ),
    ]
