# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_python3'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sort_order',
            field=models.CharField(choices=[('Al', 'Alphabetical'), ('Ca', 'Callsign'), ('Co', 'Total consumption'), ('Ra', 'Random')], default='Al', max_length=2, verbose_name='account sort order'),
        ),
    ]
